services:
  server:
    build: .
    container_name: monitoring-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 6000
    ports:
      - '6000:6000'
